server {
    listen %%interface%%:%%port%% default_server;

    include /etc/nginx/includes/server_params.conf;
    include /etc/nginx/includes/proxy_params.conf;

    location /_master_app/ {
        alias /app-root/_master_app/;
        try_files $uri $uri/ /_master_app/index.html;
    }

    location / {
        alias /app-root/_master_app/;
        index index.html;
        sub_filter_once off;
        sub_filter '<base href="/">' '<base href="%%ingress_entry%%/">';
        sub_filter '<head>' '<head><base href="%%ingress_entry%%/">';
        sub_filter 'href="/' 'href="%%ingress_entry%%/';
        sub_filter 'src="/' 'src="%%ingress_entry%%/';
        try_files $uri $uri/ /index.html;
    }

    location /_querytool_app/ {
        alias /app-root/_querytool_app/;
        index index.html;
        try_files $uri $uri/ /_querytool_app/index.html;
    }

    location /api/ {
        proxy_pass http://backend/api/;
    }
}
