---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  ingress-rendering:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Test ingress template rendering
        run: tests/test-render-nginx-ingress.sh

  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-ci.yaml@main
